### ISSUE TITLE
Adding a  new comment produces 2 confirmation messages and a screen refresh

### ISSUE THREAD

**Issue by AdHominem** [UniSiegenCSCW/questions-and-answers-portlet#15]
It just looks ugly

**Comment by l3kn** [comment]
If the page should be updated to include the new comment,
there a screen refresh has to happen somewhere
or some client side js that updates the DOM (like for the ratings component).

There does not appear to be any such js for the discussion component,
so the screen refresh is inevitable.

The duplicate confirmation messages sure is an error,
but it is buried somewhere in the discussion portlet.

A (ugly) fix would be to hide the messages via css.

Edit:

There are more problems with the discussion component,
(at least on my system) all the texts inside the component
are in english (e.g. “29 Minutes Ago”).

Would it be viable to just remove the ability to comment on questions and answers?
