### ISSUE TITLE
Kategorie-Auswahl kann nur mit ESC geschlossen werden

### ISSUE THREAD

**Issue by brodo** [UniSiegenCSCW/questions-and-answers-portlet#22]
Ich hätte gerne einen Schliessen-Button.
<img width="654" alt="kategorien" src="https://cloud.githubusercontent.com/assets/377911/20530325/52858a04-b0d3-11e6-9d32-980d837a63ae.png">

**Comment by AdHominem** [comment]
Das ist glaube ich Liferay-intern, aber können wir uns morgen mal anschauen

**Comment by l3kn** [comment]
Beim mir hat die box oben rechts einen button,
fehlt der bei dir ganz oder ist er nur sehr schlecht sichtbar?

Edit: In deinem Bild ist er auch, mal sehen ob man das irgendwie besser sichtbar machen kann

![screen](https://cloud.githubusercontent.com/assets/2060269/20562266/00a085e4-b183-11e6-97a8-9a426051d182.jpg)
